version: "3.7"

services:
### PHP Container #########################################
  youtube-php:
    container_name: youtube-php
    hostname: youtube
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html/app
    volumes:
      - ./:/var/www/html/app
    depends_on:
      - youtube-db

  ### NGINX Container #########################################
  youtube-nginx:
    container_name: youtube-nginx
    hostname: nginx
    image: nginx:1.17
    restart: unless-stopped
    depends_on:
      - youtube-php
    ports:
      - "5000:80"
    volumes:
      - ./:/var/www/html/app
      - ./docker/virtualhost.conf:/etc/nginx/conf.d/default.conf

### POSTGRESS Container #########################################
  youtube-db:
    container_name: youtube-db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: youtube
      POSTGRES_USER: youtube-user
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
    ports:
      - "54321:5432"
